# Generated by Django 3.2 on 2021-08-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(1, 'APPROVED'), (2, 'PANDING'), (3, 'REJECTED')], default=2),
        ),
    ]
