# Generated by Django 3.2 on 2021-08-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='undo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
