# Generated by Django 3.2 on 2021-08-27 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_reservation_undo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='schedule',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
